// crates/ui/src/lib.rs

// Привязываем внешние крейты к корню для бесперебойной работы макросов
pub extern crate leptos_router;
pub extern crate paste;
pub extern crate tw_merge;

// Объявление внутренних модулей библиотеки
pub mod constants;
pub mod components;
pub mod hooks;
pub mod layouts;
pub mod utils;

// Реэкспорт геометрических макетов (Layouts)
pub use layouts::absolute::AbsoluteLayout;
pub use layouts::aspect_ratio::AspectRatioLayout;
pub use layouts::centered::CenteredLayout;
pub use layouts::container::ContainerLayout;
pub use layouts::grid::GridLayout;
pub use layouts::holy_grail::HolyGrailLayout;
pub use layouts::horizontal::HorizontalLayout;
pub use layouts::masonry::MasonryLayout;
pub use layouts::spacer::SpacerLayout;
pub use layouts::split::SplitLayout;
pub use layouts::stack::StackLayout;
pub use layouts::sticky::StickyLayout;
pub use layouts::three_column::ThreeColumnLayout;
pub use layouts::two_column::TwoColumnLayout;
pub use layouts::vertical::VerticalLayout;
pub use layouts::viewport::ViewportLayout;
pub use layouts::wrap::WrapLayout;

// Реэкспорт интерактивных UI-компонентов (Components)
pub use components::accordion::*;
pub use components::action_bar::*;
pub use components::alert_dialog::*;
pub use components::avatar::*;
pub use components::animate::*;
pub use components::aspect_ratio::*;
pub use components::attachment::*;
pub use components::badge::*;
pub use components::bento_grid::*;
pub use components::bottom_nav::*;
pub use components::breadcrumbs::*;
pub use components::bubble::*;
pub use components::button_action::*;
pub use components::button_group::*;
pub use components::button::*;
pub use components::callout::*;
pub use components::card_carousel::*;
pub use components::card::*;
pub use components::carousel::*;
pub use components::charts::*;
pub use components::chat::*;
pub use components::checkbox::*;
pub use components::chips::*;
pub use components::collapsible::*;
pub use components::combobox::*;
pub use components::command::*;
pub use components::context_menu::*;
pub use components::data_grid::*;
pub use components::data_table::*;
pub use components::date_picker_dual_state::*;
pub use components::date_picker_state::*;
pub use components::date_picker::*;
pub use components::dialog::*;
pub use components::direction_provider::*;
pub use components::drag_and_drop::*;
pub use components::drawer::*;
pub use components::dropdown_menu::*;
pub use components::empty::*;
pub use components::expandable::*;
pub use components::faq_transition::*;
pub use components::field::*;
pub use components::footer::*;
pub use components::form::*;
pub use components::header::*;
pub use components::hover_card::*;
pub use components::image::*;
pub use components::input_group::*;
pub use components::input_otp::*;
pub use components::input_phone::*;
pub use components::input_prompt::*;
pub use components::input::*;
pub use components::item::*;
pub use components::kbd::*;
pub use components::label::*;
pub use components::link::*;
pub use components::marker::*;
pub use components::marquee::*;
pub use components::mask::*;
pub use components::menubar::*;
pub use components::message::*;
pub use components::multi_select::*;
pub use components::navigation_menu::*;
pub use components::pagination::*;
pub use components::popover::*;
pub use components::pressable::*;
pub use components::progress::*;
pub use components::radio_button_group::*;
pub use components::radio_button::*;
pub use components::scroll_area::*;
pub use components::select_native::*;
pub use components::select::*;
pub use components::separator::*;
pub use components::sheet::*;
pub use components::shimmer::*;
pub use components::sidenav::*;
pub use components::skeleton::*;
pub use components::slider::*;
pub use components::sonner::*;
pub use components::spinner::*;
pub use components::status::*;
pub use components::stepper::*;
pub use components::switch::*;
pub use components::table::*;
pub use components::tabs::*;
pub use components::textarea::*;
pub use components::theme_toggle::*;
pub use components::toast::*;
pub use components::toggle_group::*;
pub use components::tooltip::*;

pub use utils::Utils;

// ==========================================
// Фасады на внутренние крейты воркспейса
// ==========================================
pub use rust_lms_icons as icons;

pub mod prelude {

    pub use crate::components::accordion::*;
    pub use crate::components::action_bar::*;
    pub use crate::components::alert_dialog::*;
    pub use crate::components::alert::*;
    pub use crate::components::animate::*;
    pub use crate::components::aspect_ratio::*;
    pub use crate::components::attachment::*;
    pub use crate::components::avatar::*;
    pub use crate::components::badge::*;
    pub use crate::components::bento_grid::*;
    pub use crate::components::bottom_nav::*;
    pub use crate::components::breadcrumbs::*;
    pub use crate::components::bubble::*;
    pub use crate::components::button_action::*;
    pub use crate::components::button_group::*;
    pub use crate::components::button::*;
    pub use crate::components::callout::*;
    pub use crate::components::card_carousel::*;
    pub use crate::components::card::*;
    pub use crate::components::carousel::*;
    pub use crate::components::charts::*;
    pub use crate::components::chat::*;
    pub use crate::components::checkbox::*;
    pub use crate::components::chips::*;
    pub use crate::components::collapsible::*;
    pub use crate::components::combobox::*;
    pub use crate::components::command::*;
    pub use crate::components::context_menu::*;
    pub use crate::components::data_grid::*;
    pub use crate::components::data_table::*;
    pub use crate::components::date_picker_dual_state::*;
    pub use crate::components::date_picker_state::*;
    pub use crate::components::date_picker::*;
    pub use crate::components::dialog::*;
    pub use crate::components::direction_provider::*;
    pub use crate::components::drag_and_drop::*;
    pub use crate::components::drawer::*;
    pub use crate::components::dropdown_menu::*;
    pub use crate::components::empty::*;
    pub use crate::components::expandable::*;
    pub use crate::components::faq_transition::*;
    pub use crate::components::field::*;
    pub use crate::components::footer::*;
    pub use crate::components::form::*;
    pub use crate::components::header::*;
    pub use crate::components::hover_card::*;
    pub use crate::components::image::*;
    pub use crate::components::input_group::*;
    pub use crate::components::input_otp::*;
    pub use crate::components::input_phone::*;
    pub use crate::components::input_prompt::*;
    pub use crate::components::input::*;
    pub use crate::components::item::*;
    pub use crate::components::kbd::*;
    pub use crate::components::label::*;
    pub use crate::components::link::*;
    pub use crate::components::marker::*;
    pub use crate::components::marquee::*;
    pub use crate::components::mask::*;
    pub use crate::components::menubar::*;
    pub use crate::components::message::*;
    pub use crate::components::multi_select::*;
    pub use crate::components::navigation_menu::*;
    pub use crate::components::pagination::*;
    pub use crate::components::popover::*;
    pub use crate::components::pressable::*;
    pub use crate::components::progress::*;
    pub use crate::components::radio_button_group::*;
    pub use crate::components::radio_button::*;
    pub use crate::components::scroll_area::*;
    pub use crate::components::select_native::*;
    pub use crate::components::select::*;
    pub use crate::components::separator::*;
    pub use crate::components::sheet::*;
    pub use crate::components::shimmer::*;
    pub use crate::components::sidenav::*;
    pub use crate::components::skeleton::*;
    pub use crate::components::slider::*;
    pub use crate::components::sonner::*;
    pub use crate::components::spinner::*;
    pub use crate::components::status::*;
    pub use crate::components::stepper::*;
    pub use crate::components::switch::*;
    pub use crate::components::table::*;
    pub use crate::components::tabs::*;
    pub use crate::components::textarea::*;
    pub use crate::components::theme_toggle::*;
    pub use crate::components::toast::*;
    pub use crate::components::toggle_group::*;
    pub use crate::components::tooltip::*;

    pub use crate::layouts::*;
    pub use crate::utils::Utils;

}
