[package]
name = "rust-lms-shared"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Плоские DTO, сущности, контракты обмена и xAPI JSON-LD структуры"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["postgres", "uuid", "runtime-tokio"] }
uuid = { version = "1.10", features = ["serde", "v4"] }
